<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rosbot3">

  <!--
    Este arquivo assume que o seu domain.xacro (o arquivo que você mostrou)
    está em: $(find my_robot_description)/urdf/domain.xacro
    Ajuste o caminho abaixo conforme seu pacote.
  -->
  <xacro:include filename="$(find my_robot_description)/urdf/domain.xacro"/>

  <!-- === Parâmetros extraídos do manual Husarion (ROSbot 3) ===
       - Dimensões (com sensores): 200 x 233 x 197 mm (L x W x H)
       - Peso (com sensores): 2.84 kg
       - Standard wheel diameter: ~90 mm (há variações: 85-90 mm em docs)
       - Wheelbase: 106 mm
     Fontes: Husarion product/manual. -->
  <xacro:property name="rosbot_length" value="0.200"/>   <!-- m (200 mm) -->
  <xacro:property name="rosbot_width"  value="0.233"/>   <!-- m (233 mm) -->
  <xacro:property name="rosbot_height" value="0.197"/>   <!-- m (197 mm) -->
  <xacro:property name="rosbot_mass"   value="2.84"/>    <!-- kg (com sensores) -->

  <xacro:property name="wheel_diameter" value="0.090"/>  <!-- m (90 mm ~ doc: 85-90mm) -->
  <xacro:property name="wheel_radius"   value="${wheel_diameter / 2.0}"/>
  <xacro:property name="wheel_width"    value="0.030"/>  <!-- espessura da roda (ajustável) -->

  <xacro:property name="wheelbase" value="0.106"/>       <!-- m (106 mm) conforme doc -->
  <!-- track (largura entre eixos das rodas): documento não dá explicitamente.
       escolhi um valor plausível que cabe na largura total; ajuste se tiver desenho técnico -->
  <xacro:property name="track" value="0.170"/>           <!-- m (170 mm) - ajuste conforme necessidade -->

  <!-- chassis thickness (placa de aluminio): -->
  <xacro:property name="chassis_thickness" value="0.015"/> <!-- 15 mm (valor para visual) -->

  <!-- localização dos sensores (valores iniciais, ajuste conforme montagem real) -->
  <xacro:property name="lidar_z" value="${rosbot_height - 0.03}"/>  <!-- perto do topo -->
  <xacro:property name="camera_z" value="${rosbot_height - 0.06}"/> <!-- um pouco abaixo do LiDAR -->

  <!-- === Chassis (link base) ===
       usamos o macro solid_block do domain.xacro para criar o chassi visual/collision -->
  <xacro:solid_block
    name="chassis"
    x="0.0" y="0.0" z="${chassis_thickness/2.0}"  <!-- origin centrado no chão -->
    size_x="${rosbot_length}"
    size_y="${rosbot_width}"
    size_z="${chassis_thickness}"
    mass="${rosbot_mass * 0.6}"   <!-- parte da massa atribuída ao chassi; resto nas rodas/baterias -->
    material="DarkGrey"
    visible="true"
  />

  <!-- === Base link (frame) ===
       criamos um base_link fixo ligado ao chassi (para transform/frame do robô) -->
  <link name="base_link"/>
  <xacro:joint_fixed parent="base_link" child="chassis" x="0.0" y="0.0" z="0.0"/>

  <!-- === Rodas (4) ===
       posicionamento:
         x = +- wheelbase/2  (frente/tras)
         y = +- track/2      (esquerda/direita)
       usamos solid_cylinder para visual/collision e joint_actuated para tornar as rodas atuadas.
  -->
  <!-- roda dianteira esquerda -->
  <xacro:solid_cylinder
    name="wheel_fl"
    x="${wheelbase/2.0}" y="${track/2.0}" z="${wheel_radius}"
    roll="0" pitch="0" yaw="0"
    radius="${wheel_radius}" length="${wheel_width}"
    mass="${0.06}" material="Black" visible="true"
  />
  <xacro:joint_actuated
    name="wheel_fl"
    parent="chassis"
    child="wheel_fl"
    type="continuous"
    axis="0 1 0"    <!-- roda gira ao redor de y (ajuste se necessário) -->
    x="${wheelbase/2.0}" y="${track/2.0}" z="${wheel_radius}"
  />

  <!-- roda dianteira direita -->
  <xacro:solid_cylinder
    name="wheel_fr"
    x="${wheelbase/2.0}" y="${-track/2.0}" z="${wheel_radius}"
    radius="${wheel_radius}" length="${wheel_width}"
    mass="${0.06}" material="Black" visible="true"
  />
  <xacro:joint_actuated
    name="wheel_fr"
    parent="chassis"
    child="wheel_fr"
    type="continuous"
    axis="0 1 0"
    x="${wheelbase/2.0}" y="${-track/2.0}" z="${wheel_radius}"
  />

  <!-- roda traseira esquerda -->
  <xacro:solid_cylinder
    name="wheel_rl"
    x="${-wheelbase/2.0}" y="${track/2.0}" z="${wheel_radius}"
    radius="${wheel_radius}" length="${wheel_width}"
    mass="${0.06}" material="Black" visible="true"
  />
  <xacro:joint_actuated
    name="wheel_rl"
    parent="chassis"
    child="wheel_rl"
    type="continuous"
    axis="0 1 0"
    x="${-wheelbase/2.0}" y="${track/2.0}" z="${wheel_radius}"
  />

  <!-- roda traseira direita -->
  <xacro:solid_cylinder
    name="wheel_rr"
    x="${-wheelbase/2.0}" y="${-track/2.0}" z="${wheel_radius}"
    radius="${wheel_radius}" length="${wheel_width}"
    mass="${0.06}" material="Black" visible="true"
  />
  <xacro:joint_actuated
    name="wheel_rr"
    parent="chassis"
    child="wheel_rr"
    type="continuous"
    axis="0 1 0"
    x="${-wheelbase/2.0}" y="${-track/2.0}" z="${wheel_radius}"
  />

  <!-- === LIDAR link e câmera ===
       usamos o macro camera_link do domain.xacro para criar link óptico da câmera -->
  <xacro:link name="lidar_link"/>
  <xacro:joint_fixed parent="chassis" child="lidar_link" x="${rosbot_length/2.0 - 0.03}" y="0.0" z="${lidar_z}"/>

  <xacro:camera_link name="camera"/>
  <xacro:joint_fixed parent="chassis" child="camera" x="${rosbot_length/2.0 - 0.03}" y="0.0" z="${camera_z}" roll="0" pitch="0" yaw="0"/>

  <!-- === Inertias simples (rastreadas pelo macro inertia_none se quiser) ===
       Se quiser inercias mais realistas, troque mass e insira blocos inertia_* adequados. -->

  <!--
    Nota:
      - Ajuste 'track' (largura entre rodas), wheel_width, masses e os offsets das câmeras/LiDAR
        usando as medidas ou desenhos técnicos reais caso você os tenha.
      - Se você usa mecanum wheels, troque a geometria e orientações adequadamente.
  -->

</robot>

